# Generated by Django 6.0.6 on 2026-06-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='dealer_id',
            field=models.IntegerField(default=1),
        ),
    ]
